services:
  # Bases de datos y broker
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET}
    ports:
      - "1522:1521"
    healthcheck:
      test: ["CMD", "lsnrctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroachdb
    entrypoint: >
      sh -c "cockroach start-single-node --insecure & sleep 60 && cockroach sql --insecure --host=localhost -e 'CREATE DATABASE IF NOT EXISTS tracking;' && tail -f /dev/null"
    ports:
      - "26258:26257"
      - "8081:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "/cockroach/cockroach", "node", "status", "--insecure"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-replica:
    image: mysql:8.0
    container_name: MySQL-replica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: pedidos_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 60s
      timeout: 20s
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Microservicios
  microservicio_oracle:
    build:
      context: ../microservicio_oracle
    container_name: microservicio_oracle
    ports:
      - "5001:5001"
    depends_on:
      oracle-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: >
      sh -c "sleep 120 && python app.py"
    env_file:
      - ../microservicio_oracle/.env

  microservicio_cockroach:
    build:
      context: ../microservicio_cockroach
    container_name: microservicio_cockroach
    ports:
      - "5002:5002"
    depends_on:
      cockroachdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: >
      sh -c "sleep 30 && python app.py"
    env_file:
      - ../microservicio_cockroach/.env

  micro_mysql:
    build:
      context: ../microservicio_mysql
    container_name: micro_mysql
    ports:
      - "5003:5003"
    depends_on:
      mysql-replica:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: >
      sh -c "sleep 30 && python app.py"
    env_file:
      - ../microservicio_mysql/.env

volumes:
  cockroach-data:
  oracle-db-data:
  mysql_data:

networks:
  default:
    name: backend