version: '3.9'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    environment:
      ORACLE_PWD: admin123
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "lsnrctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroachdb
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  microservicio_oracle:
    build:
      context: ../microservicio_oracle
    container_name: microservicio_oracle
    ports:
      - "5001:5000"
    depends_on:
      - oracle-db
    environment:
      DB_USER: SYSTEM
      DB_PASSWORD: admin123
      DB_HOST: oracle-db
      DB_PORT: 1521
      DB_SERVICE: XEPDB1

  microservicio_cockroach:
    build:
      context: ../microservicio_cockroach
    container_name: microservicio_cockroach
    ports:
      - "5002:5000"
    depends_on:
      - cockroachdb
    environment:
      DB_HOST: cockroachdb
      DB_PORT: 26257
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: tracking

volumes:
  cockroach-data:
