version: '3.9'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    environment:
      ORACLE_PWD: 2108Josee
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1522:1521"
    healthcheck:
      test: ["CMD", "lsnrctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroachdb
    command: >
      start-single-node --insecure &&
      sleep 5 &&
      /cockroach/cockroach sql --insecure --execute="CREATE DATABASE IF NOT EXISTS tracking;"
    ports:
      - "26258:26257"
      - "8081:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "/cockroach/cockroach", "node", "status", "--insecure"]
      interval: 10s
      timeout: 5s
      retries: 5

  microservicio_oracle:
    build:
      context: ../microservicio_oracle
    container_name: microservicio_oracle
    ports:
      - "5001:3000"
    depends_on:
      oracle-db:
        condition: service_healthy
    entrypoint: >
      sh -c "sleep 120 && python app.py"
    env_file:
      - ../microservicio_oracle/.env

  microservicio_cockroach:
    build:
      context: ../microservicio_cockroach
    container_name: microservicio_cockroach
    ports:
      - "5002:5000"
    depends_on:
      cockroachdb:
        condition: service_healthy
    env_file:
      - ../microservicio_cockroach/.env

volumes:
  cockroach-data:
