/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
  // Forzar que incluya todas las clases básicas
  safelist: [
    "bg-blue-600",
    "bg-blue-700",
    "bg-blue-800",
    "bg-white",
    "text-white",
    "text-gray-900",
    "text-gray-600",
    "text-gray-700",
    "rounded-xl",
    "rounded-2xl",
    "shadow-lg",
    "shadow-xl",
    "p-4",
    "p-6",
    "p-8",
    "px-4",
    "px-6",
    "px-8",
    "py-3",
    "py-4",
    "py-6",
    "py-8",
    "mb-4",
    "mt-4",
    "space-x-2",
    "space-x-3",
    "space-x-4",
    "space-y-4",
    "space-y-6",
    "space-y-8",
    "flex",
    "items-center",
    "justify-between",
    "justify-center",
    "grid",
    "gap-4",
    "gap-6",
    "gap-8",
    "w-full",
    "h-full",
    "min-h-screen",
    "border",
    "border-gray-100",
    "border-gray-200",
    "transition-all",
    "duration-300",
    "hover:shadow-xl",
    "hover:-translate-y-1",
    "transform",
    "font-semibold",
    "font-bold",
    "text-sm",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-4xl",
    "bg-gradient-to-r",
    "from-blue-600",
    "via-blue-700",
    "to-blue-800",
    "hover:from-blue-700",
    "hover:via-blue-800",
    "hover:to-blue-900",
    "focus:ring-4",
    "focus:ring-blue-200",
    "lg:hidden",
    "lg:flex",
    "lg:w-72",
    "lg:pl-72",
    "hidden",
    "fixed",
    "inset-y-0",
    "left-0",
    "z-50",
    "backdrop-blur-xl",
    "bg-white/95",
    "shadow-2xl",
    "border-r",
    "flex-col",
    "flex-grow",
    "h-20",
    "sticky",
    "top-0",
    "z-40",
    "bg-white/80",
    "border-b",
    "max-w-7xl",
    "mx-auto",
    "sm:px-6",
    "lg:px-8",
  ],
}
